/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "sct.h" // including header file

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

volatile uint32_t Tick = 0; // global variable

int main(void) {
	SysTick_Config(8000000); // 1 s
	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN; // SYSCFG clock enable

	sct_init(); // initialization of the segment display
	while (1) {
		sct_value((uint16_t) Tick * 111); // sends on display not actual Tick number, but 000, 111, 222 etc
	}
}

void SysTick_Handler(void) {
	Tick++; // important handler
	if (Tick > 9) { // condition for calculation only to 9
		Tick = 0;
	}
}
